version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  udagram_api:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: 14.18.1
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Installing and building Udagram's backend
          command: |
            npm run backend:install
            npm run backend:build
      - run:
          name: Deploying Udagram's backend to Elastic Beanstalk
          command: |
            npm run backend:deploy
  udagram_frontend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: 14.18.1
      - aws-cli/setup:
          profile-name: AWS_PROFILE
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          version: 14.18.1
          name: Install and building Udagram's frontend
          command: |
            npm run frontend:install
            npm run frontend:build
      - run:
          name: Deploying the Udagram frontend to S3
          command: |
            npm run frontend:deploy
workflows:
  udagram_api_frontend_deployment:
    jobs:
      - udagram_api:
          filters:
            branches:
               only: master
      - udagram_frontend:
          filters:
            branches:
              only: master

